g_ItemPrecache =
{
	"item_bag_of_gold",
}

g_ModelPrecache =
{
	-- Item Models
	"models/props_gameplay/gold_bag.vmdl",
	
	-- Tower Pedestals
	"models/items/pedestals/pedestal_2/pedestal_2.vmdl",
	"models/heroes/pedestal/pedestal_1_small.vmdl",
	"models/heroes/pedestal/mesh/effigy_pedestal_fm16.vmdl",
	"models/heroes/pedestal/pedestal_effigy_jade.vmdl",
	"models/heroes/pedestal/mesh/effigy_pedestal_fm16_dire_wood.vmdl",
	"models/heroes/pedestal/mesh/effigy_pedestal_ti6_dire_model.vmdl",
	"models/heroes/pedestal/mesh/effigy_pedestal_wm16.vmdl",
	"models/heroes/pedestal/effigy_pedestal_frost_radiant.vmdl",
	"models/heroes/shadow_fiend/pedestal_sf.vmdl",
	"models/heroes/crystal_maiden/pedestal_cm_arcana.vmdl",
	"models/props_structures/tower_upgrade/tower_upgrade_base.vmdl",
	
	-- Towers
	"models/props_structures/rock_golem/tower_radiant_rock_golem.vmdl",
	"models/heroes/drow/drow_base.vmdl",
	"models/heroes/furion/furion.vmdl",
	"models/heroes/luna/luna.vmdl",
	"models/heroes/lina/lina.vmdl",
	"models/heroes/keeper_of_the_light/keeper_of_the_light.vmdl",
	"models/heroes/mirana/mirana.vmdl",
	"models/heroes/venomancer/venomancer.vmdl",
	"models/heroes/enchantress/enchantress.vmdl",
	"models/heroes/crystal_maiden/crystal_maiden.vmdl",
	"models/heroes/skywrath_mage/skywrath_mage.vmdl",
	"models/heroes/zeus/zeus.vmdl",
	"models/heroes/warlock/warlock.vmdl",
	"models/heroes/lone_druid/lone_druid.vmdl",
	"models/heroes/viper/viper.vmdl",
	"models/heroes/troll_warlord/troll_warlord.vmdl",
	"models/heroes/sniper/sniper.vmdl",
	"models/heroes/medusa/medusa.vmdl",
	"models/heroes/windrunner/windrunner.vmdl",
	
	-- Couriers
	-- Rare
	"models/items/courier/basim/basim.vmdl",
	"models/items/courier/blue_lightning_horse/blue_lightning_horse.vmdl",
	"models/items/courier/boooofus_courier/boooofus_courier.vmdl",
	"models/items/courier/duskie/duskie.vmdl",
	"models/items/courier/jumo/jumo.vmdl",
	"models/items/courier/beaverknight_s1/beaverknight_s1.vmdl",
	"models/items/courier/beaverknight_s2/beaverknight_s2.vmdl",
	"models/items/courier/butch_pudge_dog/butch_pudge_dog.vmdl",
	"models/courier/seekling/seekling.vmdl",
	"models/courier/doom_demihero_courier/doom_demihero_courier.vmdl",
	"models/courier/huntling/huntling.vmdl",
	"models/items/courier/krobeling/krobeling.vmdl",
	"models/courier/venoling/venoling.vmdl",
	"models/items/courier/devourling/devourling.vmdl",
	"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl",
	-- Mythical
	"models/courier/donkey_crummy_wizard_2014/donkey_crummy_wizard_2014.vmdl",
	"models/courier/donkey_unicorn/donkey_unicorn.vmdl",
	"models/courier/donkey_ti7/donkey_ti7.vmdl",
	"models/courier/greevil/gold_greevil.vmdl",
	"models/courier/trapjaw/trapjaw.vmdl",
	"models/items/courier/carty/carty.vmdl",
	"models/items/courier/faceless_rex/faceless_rex.vmdl",
	"models/courier/drodo/drodo.vmdl",
	"models/courier/otter_dragon/otter_dragon.vmdl",
	"models/items/courier/mole_messenger/mole_messenger_lvl7.vmdl",
	-- Legendary
	"models/courier/baby_rosh/babyroshan.vmdl",
	"models/courier/baby_rosh/babyroshan_elemental.vmdl",
	"models/courier/baby_rosh/babyroshan_alt.vmdl",
	"models/courier/baby_rosh/babyroshan_ti9.vmdl",
	"models/courier/baby_rosh/babyroshan_winter18.vmdl",
	-- Developer
	"models/courier/baby_rosh/babyroshan_ti10.vmdl",
	"models/courier/baby_rosh/babyroshan_ti10_dire.vmdl",
}

g_ParticlePrecache =
{
	-- Tower Stars
	"particles/arrow/star1.vpcf",
	"particles/arrow/star2_1.vpcf",
	"particles/arrow/star3_1.vpcf",
	"particles/arrow/star3_2.vpcf",
	"particles/arrow/4/star1.vpcf",
	"particles/arrow/4/star2_1.vpcf",
	"particles/arrow/4/star3_1.vpcf",
	"particles/arrow/4/star3_2.vpcf",
	"particles/arrow/5/star1.vpcf",
	"particles/arrow/5/star2_1.vpcf",
	"particles/arrow/5/star3_1.vpcf",
	"particles/arrow/5/star3_2.vpcf",
	
	-- Teleport Effects
	"particles/econ/events/ti8/teleport_start_ti8_lvl2.vpcf",
	"particles/econ/events/ti8/teleport_start_ti8_lvl3.vpcf",
	"particles/upgrade/upgrade_tier2.vpcf",
	"particles/upgrade/upgrade_tier3.vpcf",
	"particles/econ/events/ti6/blink_dagger_start_ti6.vpcf",
	
	-- Base Attacks
	"particles/tower_effects/arrow_tower_base_attack.vpcf",
	"particles/tower_effects/tower_windranger_1_base_attack.vpcf",
	"particles/tower_effects/tower_windranger_2_base_attack.vpcf",
	"particles/tower_effects/tower_windranger_3_base_attack.vpcf",
	"particles/tower_effects/tower_mirana_1_base_attack.vpcf",
	"particles/tower_effects/tower_mirana_2_base_attack.vpcf",
	"particles/tower_effects/tower_mirana_3_base_attack.vpcf",
	"particles/tower_effects/tower_luna_1_base_attack.vpcf",
	"particles/tower_effects/tower_luna_2_base_attack.vpcf",
	"particles/tower_effects/tower_luna_3_base_attack.vpcf",
	"particles/units/heroes/hero_drow/drow_base_attack.vpcf",
	"particles/units/heroes/hero_lina/lina_base_attack.vpcf",
	"particles/base_attacks/ranged_siege_good.vpcf",
	"particles/base_attacks/ranged_siege_good_explosion.vpcf",
	"particles/econ/world/towers/rock_golem/radiant_rock_golem_attack.vpcf",
	"particles/econ/items/sniper/sniper_fall20_immortal/sniper_fall20_immortal_base_attack.vpcf",
	"particles/econ/items/luna/luna_ti9_weapon/luna_ti9_base_attack.vpcf",
	"particles/tower_effects/troll_base_attack.vpcf",
	"particles/units/heroes/hero_lone_druid/lone_druid_base_attack.vpcf",
	"particles/units/heroes/hero_medusa/medusa_base_attack.vpcf",
	"particles/econ/events/ti9/rock_golem_tower/radiant_tower_attack.vpcf",
	
	-- Hero/Courier Particles
	"particles/courier_effects/trail_baby_roshan_platinum.vpcf",
	"particles/econ/courier/courier_roshan_ti8/courier_roshan_ti8.vpcf",
	"particles/econ/courier/courier_babyroshan_ti10/courier_babyroshan_ti10_ambient.vpcf",
	
	-- Item Rarity Particles
	"particles/item_effects/item_tier_1_circle.vpcf",
	"particles/item_effects/item_tier_2_circle.vpcf",
	"particles/item_effects/item_tier_3_circle.vpcf",
	"particles/item_effects/item_tier_4_circle.vpcf",
	"particles/item_effects/item_tier_5_circle.vpcf",
	
	-- Wave Particles
	"particles/creep_effects/spawn_effect.vpcf",
	"particles/creep_effects/leak_effect.vpcf",
	"particles/creep_effects/overhead_normal.vpcf",
	"particles/creep_effects/overhead_boss.vpcf",
	"particles/creep_effects/overhead_bonus.vpcf",
	
	-- Modifier Related
	"particles/units/heroes/hero_ogre_magi/ogre_magi_multicast.vpcf",
	"particles/test_particle/ogre_melee_smash.vpcf",
	"particles/units/heroes/hero_phantom_assassin/phantom_assassin_crit_impact.vpcf",
	"particles/units/heroes/hero_sandking/sandking_caustic_finale_debuff.vpcf",
	"particles/units/heroes/hero_sandking/sandking_caustic_finale_explode.vpcf",
	"particles/status_fx/status_effect_wyvern_cold_embrace.vpcf",
	"particles/act_2/frostbitten_icicle.vpcf",
	"particles/econ/events/ti9/mjollnir_shield_ti9.vpcf",
	
	-- Other
	"particles/units/heroes/heroes_underlord/abyssal_underlord_weapon_blur_c.vpcf",
	"particles/econ/items/alchemist/alchemist_midas_knuckles/alch_knuckles_lasthit_coins.vpcf",
	"particles/econ/items/ogre_magi/ogre_ti8_immortal_weapon/ogre_ti8_immortal_bloodlust_buff.vpcf",
	"particles/units/heroes/hero_undying/undying_tower_destruction.vpcf",
	"particles/radiant_fx/radiant_tower002_destruction.vpcf",
	"particles/dire_fx/dire_tower002_destruction.vpcf",
	"particles/world_tower/tower_upgrade/ti7_radiant_tower_lvl1_dest.vpcf",
	"particles/world_tower/tower_upgrade/ti7_radiant_tower_lvl3_dest.vpcf",
	"particles/world_tower/tower_upgrade/ti7_radiant_tower_lvl5_dest.vpcf",
	"particles/world_tower/tower_upgrade/ti7_radiant_tower_lvl7_dest.vpcf",
	"particles/world_tower/tower_upgrade/ti7_radiant_tower_lvl9_dest.vpcf",
	"particles/world_tower/tower_upgrade/ti7_radiant_tower_lvl11_dest.vpcf",
	"particles/units/heroes/hero_sandking/sandking_caustic_finale_explode.vpcf",
	"particles/units/heroes/hero_monkey_king/monkey_king_jump_armor_debuff_model.vpcf",
	"particles/econ/items/viper/viper_ti7_immortal/viper_poison_debuff_ti7.vpcf",
	"particles/units/heroes/hero_winter_wyvern/wyvern_arctic_burn_slow.vpcf",
	"particles/econ/events/ti8/hero_levelup_ti8.vpcf",
	"particles/units/heroes/hero_life_stealer/life_stealer_rage.vpcf",
	"particles/units/heroes/hero_windrunner/windrunner_windrun.vpcf",
	"particles/status_fx/status_effect_dark_willow_shadow_realm.vpcf",
	"particles/units/heroes/hero_dark_willow/dark_willow_shadow_realm.vpcf",
	"particles/units/heroes/heroes_underlord/abyssal_underlord_weapon_blur_a.vpcf",
	"particles/units/heroes/heroes_underlord/abyssal_underlord_weapon_blur_b.vpcf",
	"particles/units/heroes/heroes_underlord/underlord_pitofmalice.vpcf",
	"particles/units/heroes/hero_zuus/zuus_arc_lightning_.vpcf",
	"particles/units/heroes/hero_zuus/zuus_arc_lightning.vpcf",
	"particles/econ/items/zeus/lightning_weapon_fx/zuus_base_attack_arc_immortal_lightning.vpcf",
	"particles/econ/items/zeus/lightning_weapon_fx/zuus_lightning_bolt_bodyarc_immortal_lightningyzuus_lightning_bolt_bodyarc_immortal_lightning.vpcf",
	"particles/econ/items/zeus/zeus_ti8_immortal_arms/zeus_ti8_immortal_arc.vpcf",
	"particles/econ/items/shadow_fiend/sf_desolation/nvm_atk_blur_dso.vpcf",
	"particles/econ/items/shadow_fiend/sf_desolation/nvm_atk_blur_b_dso.vpcf",
}

g_ParticleFolderPrecache =
{
	"particles/buildinghelper",
	"particles/test_particle",
	"particles/act_2",
	"particles/units/heroes/hero_zuus",
	"particles/units/heroes/hero_zeus",
	"particles/econ/items/zeus",
}

g_SoundPrecache =
{
	-- Game Sounds
	"soundevents/game_sounds.vsndevts",
	"soundevents/game_sounds_main.vsndevts",
	"soundevents/game_sounds_greevils.vsndevts",
	"soundevents/game_sounds_items.vsndevts",
	"soundevents/game_sounds_ui_imported.vsndevts",
	"soundevents/soundevents_conquest.vsndevts",
	"soundevents/soundevents_dota_ui.vsndevts",
	"soundevents/music/game_sounds_music_tutorial.vsndevts",
	"soundevents/game_sounds_dungeon.vsndevts",
	"soundevents/game_sounds_dungeon_enemies.vsndevts",
	"soundevents/game_sounds_creeps.vsndevts",
	
	-- Hero Sounds
	"soundevents/game_sounds_heroes/game_sounds_nyx_assassin.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_batrider.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_centaur.vsndevts",
	"soundevents/game_sounds_roshan_halloween.vsndevts", 
	"soundevents/game_sounds_heroes/game_sounds_earthshaker.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_sandking.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_phoenix.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_ember_spirit.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_lycan.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_drowranger.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_troll_warlord.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_furion.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_luna.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_lina.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_keeper_of_the_light.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_ancient_apparition.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_jakiro.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_mirana.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_venomancer.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_enchantress.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_crystalmaiden.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_skywrath_mage.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_zuus.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_warlock.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_lone_druid.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_viper.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_sniper.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_medusa.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_windrunner.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_vengefulspirit.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_morphling.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_shadowshaman.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_meepo.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_gyrocopter.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_sven.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_abyssal_underlord.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_faceless_void.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_alchemist.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_abaddon.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_ogre_magi.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_omniknight.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_skeletonking.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_dark_willow.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_ursa.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_enigma.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_dark_seer.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_weaver.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_necrolyte.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_nevermore.vsndevts",
	"soundevents/voscripts/game_sounds_vo_medusa.vsndevts",
	"soundevents/voscripts/game_sounds_vo_sniper.vsndevts",
	"soundevents/voscripts/game_sounds_vo_viper.vsndevts",
	"soundevents/voscripts/game_sounds_vo_lone_druid.vsndevts",
	"soundevents/voscripts/game_sounds_vo_warlock.vsndevts",
	"soundevents/voscripts/game_sounds_vo_lion.vsndevts",
	"soundevents/voscripts/game_sounds_vo_gyrocopter.vsndevts",
	"soundevents/voscripts/game_sounds_vo_sven.vsndevts",
	"soundevents/voscripts/game_sounds_vo_zuus.vsndevts",
	"soundevents/voscripts/game_sounds_vo_skywrath_mage.vsndevts",
	"soundevents/voscripts/game_sounds_vo_crystalmaiden.vsndevts",
	"soundevents/voscripts/game_sounds_vo_enchantress.vsndevts",
	"soundevents/voscripts/game_sounds_vo_venomancer.vsndevts",
	"soundevents/voscripts/game_sounds_vo_jakiro.vsndevts",
	"soundevents/voscripts/game_sounds_vo_vengefulspirit.vsndevts",
	"soundevents/voscripts/game_sounds_vo_ancient_apparition.vsndevts",
	"soundevents/voscripts/game_sounds_vo_keeper_of_the_light.vsndevts",
	"soundevents/voscripts/game_sounds_vo_lina.vsndevts",
	"soundevents/voscripts/game_sounds_vo_meepo.vsndevts",
	"soundevents/voscripts/game_sounds_vo_abyssal_underlord.vsndevts",
	"soundevents/voscripts/game_sounds_vo_troll_warlord.vsndevts",
	"soundevents/voscripts/game_sounds_vo_drowranger.vsndevts",
	"soundevents/voscripts/game_sounds_vo_furion.vsndevts",
	"soundevents/voscripts/game_sounds_vo_mirana.vsndevts",
	"soundevents/voscripts/game_sounds_vo_enigma.vsndevts",
	"soundevents/voscripts/game_sounds_vo_shadowshaman.vsndevts",
	"soundevents/voscripts/game_sounds_vo_luna.vsndevts",
	"soundevents/voscripts/game_sounds_vo_faceless_void.vsndevts",
	"soundevents/voscripts/game_sounds_vo_windrunner.vsndevts",
	"soundevents/voscripts/game_sounds_vo_wisp.vsndevts",
	"soundevents/game_sounds_heroes/game_sounds_life_stealer.vsndevts",
	"soundevents/voscripts/game_sounds_vo_lycan.vsndevts",
	"soundevents/voscripts/game_sounds_vo_sandking.vsndevts",
	"soundevents/voscripts/game_sounds_vo_ogre_magi.vsndevts",
	"soundevents/voscripts/game_sounds_vo_broodmother.vsndevts",
	"soundevents/voscripts/game_sounds_vo_invoker.vsndevts",
	"soundevents/voscripts/game_sounds_vo_nevermore.vsndevts",
	
	-- Announcers
	"soundevents/voscripts/game_sounds_vo_announcer_dlc_bastion.vsndevts",
	"soundevents/voscripts/game_sounds_vo_announcer_dlc_darkest_dungeon.vsndevts",
	"soundevents/voscripts/game_sounds_vo_announcer_dlc_workshop_pirate.vsndevts",
	"soundevents/voscripts/game_sounds_vo_announcer_dlc_fallout4.vsndevts",
	"soundevents/voscripts/game_sounds_vo_announcer.vsndevts",
}
